config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"
  resources :events, :attendances, :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: 'User'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :attendances
  has_many :attendees, class_name: 'User', through: :attendances, source: 'attendee'

  scope :past, -> { where('date < ?', DateTime.now) }
  scope :upcoming, -> { where('date >= ?', DateTime.now) }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, foreign_key: 'creator_id'
  has_many :attendances, foreign_key: 'attendee_id'
  has_many :attended_events, class_name: 'Event', through: :attendances, source: 'event'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def new
    @attendance = Attendance.new
  end

  def create
    @attendance = Attendance.new(attendance_params)
    if @attendance.save
      redirect_to current_user
    else
      render :new
    end
  end

  def show
    @attendance = Attendance.find(params[:id])
  end

  private

  def attendance_params
    params.require(:attendance).permit(:attendee_id, :event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @passed_events = Event.past
    @upcoming_events = Event.upcoming
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @attendance = Attendance.new
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user_events = current_user.events.all
    @my_upcoming_events = current_user.attended_events.upcoming
    @my_past_events = current_user.attended_events.past
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/show.html.erb
<h1>You have registered to attend that event</h1>

app/views/events/create.html.erb
<h1>New Event</h1>

<%= form_with model: @event do |form| %>
<% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= form.label :name, "name" %> <br/>
    <%= form.text_field :name, placeholder: "Enter event name"  %> <br/>
    <%= form.label :location, "location" %> <br/>
    <%= form.text_field :location, placeholder: "Enter event location" %> <br/>
    <%= form.label :date, "date" %> <br/>
    <%= form.datetime_field :date %> <br/>
    <%= form.submit "Submit this form" %>
  <% end %>

app/views/events/index.html.erb
<h1>Events List</h1>
<h2>Upcoming events</h2>
<ul>
  <% @upcoming_events.each do |event| %>
    <li>
      <%= link_to event.name, event %>
    </li>
  <% end %>
</ul>

<h2>Passed events</h2>
<ul>
  <% @passed_events.each do |event| %>
    <li>
      <%= link_to event.name, event %>
    </li>
  <% end %>
</ul>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_with model: @event do |form| %>
<% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= form.label :name, "name" %> <br/>
    <%= form.text_field :name, placeholder: "Enter event name"  %> <br/>
    <%= form.label :location, "location" %> <br/>
    <%= form.text_field :location, placeholder: "Enter event location" %> <br/>
    <%= form.label :date, "date" %> <br/>
    <%= form.datetime_field :date %> <br/>
    <%= form.submit "Submit this form" %>
  <% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<p><%= @event.location %></p>

<p><%= @event.date %></p>
<% if @event.attendees.include?(current_user)%>
  <p>You are already attending this event</p>
<%else%>
  <%= link_to 'Attend',attendances_path(attendance: {event_id:@event.id, attendee_id:current_user.id}), method: :post ,class:"btn bg-primary text-white"%>
<% end %>

<h2>List of attendees</h2>
<ul>
      <% @event.attendees.each do |attendee| %>
          <li>
            <%= attendee.email %>
            </li>
      <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous"> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header class="navbar navbar-top navbar-inverse">
      <div class="container">
      <span class="navbar-brand">
        <%= link_to "Private Events", root_path %>
      </span>
        <nav>
          <ul class="navbar-nav">
            <li ><%= link_to "Home", root_path %></li>
            <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Create New Event", new_event_path%></li>
            <li class="nav-item"><%= link_to "Show User Events", user_path(current_user)%></li>
            <li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li class="nav-item"><%= link_to "Sign Up or Sign In", new_user_registration_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main> 
  </body>
</html>

app/views/users/show.html.erb
<div class="center jumbotron">
  <h1>List of Events you are attending</h1>

  <h2>Upcoming events</h2>
  <ul>
    <% @my_upcoming_events.each do |event| %>
      <li>
        <%= event.name%>
      </li>
    <% end %>
  </ul>

  <h2>Past events</h2>
  <ul>
    <% @my_past_events.each do |event| %>
      <li>
        <%= event.name%>
      </li>
    <% end %>
  </ul>

  <h1>List of your created events</h1>
  <ol>
    <% @user_events.each do |event| %>
      <li>
        <%= event.name%>
      </li>
    <% end %>
  </ol>
</div>